//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Language.API {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CreateOrderControllerMsg {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CreateOrderControllerMsg() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Domain.Language.API.CreateOrderControllerMsg", typeof(CreateOrderControllerMsg).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe ao menos um produto no seu pedido.
        /// </summary>
        public static string TryValidateModel_Error_00001 {
            get {
                return ResourceManager.GetString("TryValidateModel_Error_00001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe ao menos um item para ser adicionado ou atualizado no pedido.
        /// </summary>
        public static string TryValidateModel_Error_00002 {
            get {
                return ResourceManager.GetString("TryValidateModel_Error_00002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe ao menos um item para ser removido do seu pedido.
        /// </summary>
        public static string TryValidateModel_Error_00003 {
            get {
                return ResourceManager.GetString("TryValidateModel_Error_00003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe ao menos um status.
        /// </summary>
        public static string TryValidateModel_Error_00004 {
            get {
                return ResourceManager.GetString("TryValidateModel_Error_00004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe ao menos um usuário.
        /// </summary>
        public static string TryValidateModel_Error_00005 {
            get {
                return ResourceManager.GetString("TryValidateModel_Error_00005", resourceCulture);
            }
        }
    }
}
